# dans un namespace "projet"
# deploiement de 1 pod d'une base de données mysql (attention, on parle d'une base de données!!!!!!)
# deploiement de 3 pods wordpress
# service d'accès à mysql interne au cluster
# service d'accès à l'application wordpress depuis l'extérieur


#deployment rabbitmq
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: projet
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-pod
  template:
    metadata:
      labels:
        app: rabbitmq-pod
    spec:
      containers:
      - image: bmehdi78/rabbitmq:3-management 
        name: rabbitmq-cont
        ports:
        - name: port5672
          containerPort: 5672
        - name: port15672
          containerPort: 15672
      restartPolicy: Always

---
#service rabbitmq
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: projet
spec:
  selector:
    app: rabbitmq-pod
  ports:                                                        # Mettre le même que celui indiqué plus haut dans le deployement
    - name: port5672
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: port15672
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP


