# dans un namespace "projet"
# deploiement de 1 pod d'une base de données mysql (attention, on parle d'une base de données!!!!!!)
# deploiement de 3 pods wordpress
# service d'accès à mysql interne au cluster
# service d'accès à l'application wordpress depuis l'extérieur

#deployment sql-data
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: projet
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-pod
  template:
    metadata:
      labels:
        app: mssql-pod
    spec:
      containers:
      - name: mssql
        image: bmehdi78/mssql-linux  # mssql-linux:latest or microsoft/mssql-server-linux:2017-latest
        ports:
        - containerPort: 1433
      restartPolicy: Always



---
#service sql-data
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: projet
spec:
  selector:
    app: mssql-pod
  ports:                                                        # Mettre le même que celui indiqué plus haut dans le deployement
    - protocol : TCP
      port: 5433
      targetPort: 1433
  type: ClusterIP
