# dans un namespace "projet"
# deploiement de 1 pod d'une base de données mysql (attention, on parle d'une base de données!!!!!!)
# deploiement de 3 pods wordpress
# service d'accès à mysql interne au cluster
# service d'accès à l'application wordpress depuis l'extérieur


#deployment user-data
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdata-deployment
  namespace: projet
  labels:
    app: userdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdata-pod
  template:
    metadata:
      labels:
        app: userdata-pod
    spec:
      containers:
      - image: bmehdi78/redis #redis:latest
        name: userdata-cont
        ports:
        - containerPort: 6379
      restartPolicy: Always

---
#service user-data
apiVersion: v1
kind: Service
metadata:
  name: userdata-service
  namespace: projet
spec:
  selector:
    app: userdata-pod
  ports:                                                        # Mettre le même que celui indiqué plus haut dans le deployement
    - port: 6379
      targetPort: 6379
  type: ClusterIP


